categories:
  - get-started # Get Started
  - build-your-first-document-parsing-api # API Builder
  - apis-overview #Mindee's REST API
  - tutorials #Off-the-shelf APIs
  - integration #Integrations
  - librairies #SDKs
