name: Synchronize README.io documentation with GitHub
on:
  push:
    branches:
      - main

jobs:
  push_new_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setting up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing sinch-readme-sync
        run: npm ci --ignore-scripts -g sinch-readme-sync

      - name: Get modified files
        id: changed-files
        uses: tj-actions/changed-files@v11.7

      - name: Push new documentation changes
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            #readme-sync push -f $file
          done
