name: Synchronize README.io documentation with GitHub
on:
  push:
    branches:
      - main

jobs:
  push_new_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setting up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing sinch-readme-sync
        run: npm i --ignore-scripts -g @sinch/readme-sync

      - name: Push new documentation changes
        run: readme-sync --apikey ${{ secrets.APIKEY }} --docsversion ${{ secrets.DOCSVERSION }} -d . push

      - if: failure()
        run: echo "Something went wrong"
